services:
  - type: web
    name: rahul-md-bot
    env: node
    branch: main
    repo: https://github.com/Rahul-Rd-Bot/rahul-md-bot.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_INFO
        value: ʀᴀʜᴜʟ;ʀᴀʜᴜʟ;https://i.imgur.com/1PvEqb8.jpeg
      - key: WARN_COUNT
        value: 3
      - key: AUTO_STATUS_VIEWS
        value: false
      - key: MEDIA_DATA
        value: ʀᴀʜᴜʟ;ʀᴀʜᴜʟ;https://i.imgur.com/1PvEqb8.jpeg
      - key: HANDLER
        value: /
      - key: WORK_TYPE
        value: private
      - key: SERVER
        value: render
      - key: STICKER_PACKNAME
        value: ʀᴀʜᴜʟ
      - key: AUDIO_DATA
        value: ʀᴀʜᴜʟ;ʀᴀʜᴜʟ;https://i.imgur.com/1PvEqb8.jpeg
      - key: SUDO
        value: 919547261290
      - key: SERVERURL
        value:
      - key: DATABASE_URL
        sync: false
